In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("csv_files/StudentsPerformance.csv")

#### Assigne

#### it usuage:
1. to add multiple series as a cloumn in dataframe

In [13]:
df_copy = df.copy()

##### making randon series to add as new column

In [6]:
value_1 = np.random.randint(0, 100, 1000)
value_2 = np.random.randint(0, 100, 1000)

In [12]:
df_copy.assign(**{'columne 1': value_1, 'columne 2' : value_2})

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,columne 1,columne 2
0,female,group B,bachelor's degree,standard,none,72,72,74,71,70
1,female,group C,some college,standard,completed,69,90,88,88,40
2,female,group B,master's degree,standard,none,90,95,93,24,21
3,male,group A,associate's degree,free/reduced,none,47,57,44,53,93
4,male,group C,some college,standard,none,76,78,75,76,12
...,...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,19,31
996,male,group C,high school,free/reduced,none,62,55,55,47,44
997,female,group C,high school,free/reduced,completed,59,71,65,96,41
998,female,group D,some college,standard,completed,68,78,77,86,86
999,female,group D,some college,free/reduced,none,77,86,86,70,41

#### Insert

##### it usuage:
1. to add comlumn in specific column index

In [14]:
df_copy.insert(1, "Test_column", value_1)

In [15]:
df_copy

,gender,Test_column,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,71,group B,bachelor's degree,standard,none,72,72,74
1,female,88,group C,some college,standard,completed,69,90,88
2,female,24,group B,master's degree,standard,none,90,95,93
3,male,53,group A,associate's degree,free/reduced,none,47,57,44
4,male,76,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...,...
995,female,19,group E,master's degree,standard,completed,88,99,95
996,male,47,group C,high school,free/reduced,none,62,55,55
997,female,96,group C,high school,free/reduced,completed,59,71,65
998,female,86,group D,some college,standard,completed,68,78,77
999,female,70,group D,some college,free/reduced,none,77,86,86