In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("csv_files/StudentsPerformance.csv")

### Mathmatic operation

1. .sum()
2. .count()
3. .mean()
4. .std()
5. .max()
6. .min()
7. .round()

##### easy way for mathmatic value use '.describe()'

In [10]:
clone_df = df.copy()
clone_df.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [20]:
clone_df[["reading score", "math score", "writing score"]].sum()

reading score    69169
math score       66089
writing score    68054
dtype: int64

In [21]:
clone_df.describe()

       math score  reading score  writing score
count  1000.00000    1000.000000    1000.000000
mean     66.08900      69.169000      68.054000
std      15.16308      14.600192      15.195657
min       0.00000      17.000000      10.000000
25%      57.00000      59.000000      57.750000
50%      66.00000      70.000000      69.000000
75%      77.00000      79.000000      79.000000
max     100.00000     100.000000     100.000000